repos:
  - repo: https://github.com/fsouza/autoflake8
    rev: v0.3.2
    hooks:
    - id: autoflake8

  - repo: https://github.com/myint/autoflake
    rev: 'v1.4'
    hooks:
    - id: autoflake
      args: ['--in-place', '--remove-all-unused-imports', '--ignore-init-module-imports']
      name: autoflake
      entry: autoflake
      language: python
      'types': [python]
      require_serial: true
      exclude: ^tests/codegen/snapshots/python/

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        exclude: ^tests/codegen/snapshots/python/

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.2
    hooks:
      - id: prettier
        files: '^docs/.*\.mdx?$'

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-toml

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args: ['--line-length=79']
        exclude: ^tests/codegen/snapshots/python/

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies: ["flake8-eradicate==1.2.0"]
        exclude: ^tests/codegen/snapshots/python/
  - repo: local
    hooks:
      - id: create requirements
        name: create requirements
        entry: sh create_requirements.sh
        language: system
        always_run: true
        pass_filenames: true
      - id: store test results
        name: store test results
        entry: sh store_test_results.sh
        language: system
        always_run: true
        pass_filenames: true
